config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products, only: [:show] do
      collection do
        get 'search'
      end
    end
    resources :categories, only: [:show]
    root                            to: 'home#index'
    get '/',                        to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :option_values_all, -> (value) { includes(:option_type).where(spree_option_types: { presentation: value }) }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  def related_products
    Spree::Product.in_taxons(taxons).includes(master: [:default_price, :images]).distinct.where.not(id: id)
  end

  def self.count_products_with_option_value(taxon, option_value)
    Spree::Product.in_taxon(taxon).includes(option_types: :option_values).where(spree_option_values: { name: option_value }).count
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(name description)
  end

  def ransackable_associations(auth_object = nil)
    %w(stores variants_including_master master variants)
  end

  scope :filter_by_taxon, -> (taxon) { in_taxon(taxon).includes(master: [:default_price, :images]).includes(option_types: :option_values).distinct }

  scope :filter_by_option_value, -> (value) do
    includes(master: [:default_price, :images]).includes(option_types: :option_values).where(spree_option_values: { name: value })
  end

  scope :filter_by_option_2value, -> (value1, value2) do
    includes(master: [:default_price, :images]).includes(option_types: :option_values).where(spree_option_values: { name: value1, name: value2 })
  end

  scope :sort_by_newness, -> {reorder(available_on: :desc)}
  scope :sort_by_oldness, -> {reorder(available_on: :asc)}
  scope :sort_by_price_desc, -> {unscope(:order).descend_by_master_price}
  scope :sort_by_price_asc, -> {unscope(:order).ascend_by_master_price}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_search

  def set_search
    @q = Spree::Product.ransack(params[:q])
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxon_roots = Spree::Taxon.where(depth: 0).includes(:children)
    @colors = Spree::OptionValue.option_values_all("Color")
    @sizes = Spree::OptionValue.option_values_all("Size")

    if params[:color].present? && params[:size].present?
      @products = Spree::Product.filter_by_taxon(@taxon).filter_by_option_2value(params[:color], params[:size])
    elsif params[:color].present? || params[:size].present?
      option_value = params[:color].present? ? params[:color] : params[:size]
      @products = Spree::Product.filter_by_taxon(@taxon).filter_by_option_value(option_value)
    else
      @products = Spree::Product.filter_by_taxon(@taxon)
    end

    if params[:sort].present?
      case params[:sort]
      when "sort_by_newness"
        @products = @products.sort_by_newness
      when "sort_by_oldness"
        @products = @products.sort_by_oldness
      when "sort_by_price_desc"
        @products = @products.sort_by_price_desc
      when "sort_by_price_asc"
        @products = @products.sort_by_price_asc
      end
    else
      @products = @products.sort_by_newness
    end


    @partial = params[:view] || 'list'
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW = 6
  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).order(available_on: :desc).limit(MAX_NEW)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.limit(MAX_RELATED)
  end

  def search
    @search_products = @q.result.page(params[:page]).includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'BIGBAG Store'
    if page_title.blank?
      return base_title
    else
      return "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">

  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12 form-inline">
          <ul class="list-inline pull-right">
            <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= search_form_for(@q, url: search_potepan_products_path, method: :get, enforce_utf8: false) do |f| %>
                    <span class="input-group form-inline">
                      <%= f.text_field :name_or_description_cont, class: "form-control", placeholder: "Search…", aria_describedby: "basic-addon2" %>
                      <%= f.submit "検索", class: "input-group-addon addPointer", id: "basic-addon2" %>
                    </span>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
      <%= link_to image_tag("img/logo.png", :alt => ""), potepan_root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li class="active"><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li><a href="single_product.html">Single Product</a></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_grid.html.erb
<div class="row">
  <% if products.present? %>
    <% products.each do |product| %>
      <div class="col-sm-4 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% product.images.each_with_index do |image, i| %>
                  <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag(image.attachment.url(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="productCaption clearfix">
            <h5>
              <%= link_to(product.name, potepan_product_path(product.id)) %>
            </h5>
            <h3><%= product.display_price %></h3>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/potepan/categories/_list.html.erb
<div class="row productListSingle">
  <% if products.present? %>
    <% products.each do |product| %>
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% product.images.each_with_index do |image, i| %>
                  <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag(image.attachment.url(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to(product.name, potepan_product_path(product.id)) %>
            </h4>
            <p><%= product.description %></p>
            <h3><%= product.display_price %></h3>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">Product categories</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxon_roots.each do |taxon_root| %>
            <%= render 'sidebar_tree', taxon: taxon_root %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="panel panel-default filterNormal" id="filter-by-color">
    <div class="panel-heading">filter by Color</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <% colors.each do |color| %>
          <% number = Spree::Product.count_products_with_option_value(taxon, color.name) %>
          <% unless number.zero? %>
            <li id = "<%= "selected-option-value" if color.name==params[:color] %>">
              <%= link_to(potepan_category_path(id: taxon.id, color: color.name, size: params[:size])) do %>
                <%= color.name %><span><%= "(#{number})" %></span>
              <% end %>
            </li>
          <% end %>
        <% end %>
        <%= link_to(potepan_category_path(id: taxon.id, color: nil, size: params[:size])) do %>
          reset filter
        <% end %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">filter by Size</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <% sizes.each do |size| %>
          <% number = Spree::Product.count_products_with_option_value(taxon, size.name) %>
          <% unless number.zero? %>
            <li id = "<%= "selected-option-value" if size.name==params[:size] %>">
              <%= link_to(potepan_category_path(id: taxon.id, size: size.name, color: params[:color])) do %>
                <%= size.name %><span><%= "(#{number})" %></span>
              <% end %>
            </li>
          <% end %>
        <% end %>
        <%= link_to(potepan_category_path(id: taxon.id, color: params[:color], size: nil)) do %>
          reset filter
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_sidebar_tree.html.erb
<li>
  <% if taxon.children.present? %>
    <%= link_to('javascript:void(0);', data: {toggle:"collapse", target:"##{taxon.name}"}) do %>
      <%= taxon.name %><i class="fa fa-plus" id="side-icon-right"></i>
    <% end %>
  <% else %>
    <%= link_to(potepan_category_path(taxon.id)) do %>
      <i class="fa fa-caret-right" id="side-icon-left" aria-hidden="true"></i><%= taxon.name %><span><%= "(#{taxon.products.count})" %></span>
    <% end %>
  <% end %>
  <ul id="<%= taxon.name %>" class="collapse collapseItem">
    <% taxon.children.each do |child| %>
      <%= render 'sidebar_tree', taxon: child %>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'layouts/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar', taxon: @taxon, taxon_roots: @taxon_roots, colors: @colors, sizes: @sizes, products: @products %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_tag(request.path, method: :get, enforce_utf8: false) do %>
              <%= hidden_field_tag :color, params[:color] %>
              <%= hidden_field_tag :size, params[:size] %>
              <%= select_tag "sort", options_for_select([
                ["新着順", "sort_by_newness"],
                ["安い順", "sort_by_price_asc"],
                ["高い順", "sort_by_price_desc"],
                ["古い順", "sort_by_oldness"]], selected: params[:sort]||"sort_by_newness"), {onchange: 'submit(this.form);'} %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <%= link_to(potepan_category_path(id: @taxon.id, view: :grid), class: "btn btn-default", remote: true) do %>
                <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
              <% end %>
              <%= link_to(potepan_category_path(id: @taxon.id, view: :list), class: "btn btn-default", remote: true) do %>
                <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
              <% end %>
            </div>
          </div>
        </div>
        <div id="product_form">
          <%= render @partial, taxon: @taxon, products: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners_logo_slider' %>

app/views/potepan/categories/show.js.erb
$("#product_form").html("<%= escape_javascript(render "#{@partial}", products: @products) %>");

app/views/potepan/home/index.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data: { bgposition: "center center", bgfit: "cover", bgrepeat: "no-repeat" }) %>
        </li>
      </ul>
    </div>
  </div>
</div>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Shirts</a></div>
          </div>
          <div class="caption">
            <h4>Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Bags</a></div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Denim</a></div>
          </div>
          <div class="caption">
            <h4>Denim</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>新着商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <% @new_products.each_with_index do |new_product,index| %>
            <div class="slide">
              <div class="productImage<%= " clearfix" if index==0 %>">
                <%= image_tag(new_product.display_image.attachment.url(:large)) %>
              </div>
              <div class="productCaption<%= " clearfix" if index==0 %>">
                <%= link_to(potepan_product_path(new_product.id)) do %>
                  <h5><%= new_product.name %></h5>
                <% end %>
                <h3><%= new_product.display_price %></h3>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- PORDUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <!-- <option value="0">数</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_main_content_section.html.erb
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% product.images.each_with_index do |image,i| %>
                  <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag(image.attachment.url(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% product.images.each_with_index do |image,i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag(image.attachment.url(:small)) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><%= link_to "一覧ページへ戻る", potepan_category_path(product.taxons.first.id), class: "fa fa-reply", 'aria-hidden': true %></li>
              <!--<li><a href="product_grid_left_sidebar.html"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li> -->
              <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
            </ul>
            <h2><%= product.name %></h2>
            <h3><%= product.display_price %></h3>
            <p><%= product.description %></p>
            <span class="quick-drop">
              <% if product.option_types.find_by(presentation: "size") %>
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <% product.option_types.find_by(presentation: "size").option_values.each_with_index do |option_value,index| %>
                    <option value="<%= index %>"><%= option_value.presentation %></option>
                  <% end %>
                </select>
              <% end %>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
              <!--   <option value="0">Qty</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%= render 'related_products', related_products: related_products %>
  </div>
</section>